# Generated by Django 5.1.1 on 2024-09-11 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_cart_rename_product_products_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="products",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="products",
            new_name="product",
        ),
    ]
